Third Party Page
WSU-4110/Crypto pull request #49
Opened 2021-07-08 23:57 UTC by snshamwow

Implementing a search feature using NewsAPI to find crypto news.

2021-07-09 02:13 UTC, IKwiotek requested changes

2021-07-09 02:13 UTC, IKwiotek commented on src/components/ThirdPartyEducation.js
> +        const apiKey = '8577c03e48d246b3b0ca7329456e3e84'
The API key should not be included in source control. I mentioned this to all other teams during the Sprint 2 presentation. 

Once the key is removed from source control, it should be rotated to ensure that it cannot be used maliciously.

2021-07-25 22:31 UTC, IKwiotek approved these changes
API Key is now removed, Approving PR.

2021-07-26 19:14 UTC, IKwiotek commented
@vionaveseli I added you as an approver for this PR.

As discussed, we will need to save the API Key on our local machine and insert it into the TPE file before deploying. I'm not thrilled with this approach, but until we figure out how to pull the `newsapikey` environment variable from the back-end, this will suffice.

2021-07-26 19:15 UTC, IKwiotek commented
We will want to deploy these changes to the hosted site prior to approving the PR as well.

2021-07-26 20:52 UTC, gj6645 approved these changes
Approved. This should be one of the lasts merges we have in the main ensure other members don't run into problems when adding/running main or Sadeem should send the api key to each member so they can add it in on their local machine.

2021-07-26 21:08 UTC, merged